 services:

  postgresql:
    image: postgres:14-alpine
    container_name: bot_service
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_requests
      - PGDATA=/data/postgres




